Repository schubergphilis/terraform-gitlab-mcaf-project, pull requests merged in 2024-04, with the labels that each got.

#8 feature: add prevent_secrets variable to project
  .github/workflows/terraform-validation.yaml
  .gitignore
  .pre-commit-config.yaml
  README.md
  examples/basic/main.tf
  examples/complete/main.tf
  examples/complete/versions.tf
  examples/custom-branch-protection/main.tf
  examples/custom-branch-protection/versions.tf
  main.tf
  tests/complete.tftest.hcl
  tests/setup/main.tf
  variables.tf
Labels: feature

#9 feat: add additional settings and change default for prevent_secrets
  .github/workflows/terraform-validation.yaml
  .pre-commit-config.yaml
  README.md
  examples/complete/main.tf
  main.tf
  tests/complete.tftest.hcl
  variables.tf
Labels: enhancement, feature

#10 fix: update actions
  .github/workflows/release-drafter.yaml
  .github/workflows/terraform-validation.yaml
Labels: security

#11 feat: add security best practice CKV_GLB_4
  README.md
  main.tf
  tests/setup/main.tf
  variables.tf
Labels: enhancement, feature

#12 bug: remove_source_branch_after_merge, default should be true
  README.md
  examples/complete/main.tf
  tests/complete.tftest.hcl
  variables.tf
Labels: bug

#13 feat: add project and mr approval rules
  README.md
  examples/complete/main.tf
  main.tf
  tests/complete.tftest.hcl
  variables.tf
Labels: enhancement, feature

#14 feature: cicd variables input for given project
  README.md
  examples/complete/main.tf
  main.tf
  tests/complete.tftest.hcl
  variables.tf
Labels: enhancement, feature
